service: aws-ruby-ses
useDotenv: true

frameworkVersion: '2'

provider:
  name: aws
  region: us-east-1
  runtime: ruby2.7
  memorySize: 256
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
          Resource:
            - "arn:aws:ses:${self:provider.region}:*:*"
  timeout: 10
  environment:
    stage: ${sls:stage}
    region: ${self:provider.region}
    service: ${self:service}
  logRetentionInDays: 30
  tags:
    Application: ${self:service}
    Stage: ${sls:stage}
  lambdaHashingVersion: 20201221

functions:
  send-email:
    handler: src/handlers/send_email/handler.run
    environment:
      SENDER: ${env:SENDER}
      RECIPIENT: ${env:RECIPIENT}

plugins:
  - serverless-ruby-layer
custom:
  rubyLayer:
    include_functions:
      - send-email
